### ISSUE TITLE
iOS PacketSender crashes when phone is unlocked

### ISSUE THREAD

**Issue by ajhoddinott** [dannagle/PacketSender#117]
#### What OS?

- [ ] Windows
- [ ] Mac
- [ ] Linux (Which distro?)
- [x] iOS 

iOS 11.4 (15F79) 
iPhone SE (A1723)
Packet Sender Mobile v1.0.9

#### Description of issue

1) Open Packet Sender
2) Lock phone
3) Unlock phone

Packet sender crashes, returning to the home screen.

1) Open Packet Sender
2) Switch to another app
3) Switch back to Packet Sender

Works fine

1) Open Packet Sender
2) Switch to another app
3) Lock phone
4) Unlock phone
5) Switch back to Packet Sender

Packet sender crashes, returning to the home screen.

**Comment by dannagle** [comment]
This one was difficult to track down. The problem looks to be in the listening servers. Packet Sender Mobile listens for incoming connections. When iOS locks the screen, it also stops those servers. When it unlocks, the server is dead, and PS Mobile gets confused. My guess once I dig further, I'll find the real culprit is the TCP server. Operating systems and virus scanners love killing app-hosted TCP servers. 

I don't have a fix yet. I need more time. At least I now know where to dig. I need to do a server stop/restart mechanism when Packet Sender loses focus.


BTW, for future issues, Packet Sender Mobile has its own repo: 
https://github.com/dannagle/Packet_Sender_Mobile

GitHub does not have issue migration between repos, so this discussion can stay here.

**Comment by ajhoddinott** [comment]
In case it’s of any relevance, I haven’t yet used TCP at all since installing on iOS, only UDP. 

Sorry for the repo confusion. I followed the support link in the iOS App Store, which took me to the packetsender.com top page, and from there the File A Ticket link brought me here.

**Comment by dannagle** [comment]
The TCP server is running whether it is used or not. It's not used often, but those that need it really appreciate having it. 

No prob about repo confusion. I'm just happy you told me about it so I can fix it. I hope to push an update out this weekend.

**Comment by dannagle** [comment]
The update is working its way through the app store process now.

**Comment by dannagle** [comment]
Update is now live.

**Comment by ajhoddinott** [comment]
I saw thanks, and I confirm both the crash sequences are fixed!

**Comment by dannagle** [comment]
Glad to hear that. Thanks for telling me about the bug and how to recreate it.
