### ISSUE TITLE
Package never receive on 127.0.0.1

### ISSUE THREAD

**Issue by btbensoft** [dannagle/PacketSender#128]
#### OS

Windows Server 2016

#### Description of issue

When i tried to send a package with my server to the localhost (i.e 127.0.0.1), I never received response
Even if i allow the port in the firewall

See picture 
![image](https://user-images.githubusercontent.com/36570423/49388150-afca8000-f723-11e8-917b-469ce85ddd6e.png)

PS : but on my local PC all work well, i got this problem only on my servers...

Did i miss rule/configuration?

**Comment by dannagle** [comment]
I don't have a copy of Win Server to test, so I can only offer wild speculations.

127.0.01 "shouldn't" require a firewall rule because the packet never leaves the OS, but perhaps Win Server is different. 

Win Server may not allow a packet to be sent to itself on the same port. I think it has a specialized network stack. That'd be an odd restriction, but I can see the reasoning for that... why would you need a copy of a packet you just sent?

Maybe you have 2 applications fighting over the same port: 55014? Perhaps something crashed and port 55014 has not recovered. If you have Packet Sender set to dynamic binding (port 0), just click the toggle button off/on in the button right to have it choose a free port.

Packet Sender has an IPv6-only mode. Make sure you are not set to IPv6-only. 

If you have automatic replies turned on, Packet Sender can crash if you tell it to send to itself (it will rapidly auto-reply to itself to infinity). 

You can attempt your test with 2 instances of Packet Sender if you use dynamic binding. Launch it twice and have 1 talk to the other. 

I hope one of those ideas help you.

**Comment by dannagle** [comment]
If you know you only need IPv4, you can try setting Packet Sender to IPv4-only mode. The sockets bind slightly different. It might help. I don't have a copy of Win Server, so I am sorry I cannot be more help.

**Comment by dannagle** [comment]
The latest version of Packet Sender now binds IPv4-only by default. That may help this ticket.
