### ISSUE TITLE
Setting TCP Server Port not working

### ISSUE THREAD

**Issue by TreyStewart** [dannagle/PacketSender#131]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

Setting the TCP Server Port in the Network Settings to anything other than 0 (9009 for my purposes) has no effect.  The packet is still sent from Random ports.
![image](https://user-images.githubusercontent.com/38989216/51005814-4a716800-14f5-11e9-8382-428076f3b6c3.png)
![image](https://user-images.githubusercontent.com/38989216/51005889-93c1b780-14f5-11e9-8038-3c066d49298c.png)

**Comment by dannagle** [comment]
This is working as designed. That settings page is binding the server. Not the client. Packet Sender is capable of listening as well as sending packets. The clients and servers can operate independent of each other.

TCP clients (almost) always send from a dynamic port. Rarely does the source port matter for TCP since the session is negotiated upon connecting and held until terminated. UDP being stateless is sent from the binded UDP server port because that is usually the only way to get a response. Most UDP servers by design will reply to source ports. 

If your setup requires a particular source port for TCP, the command line supports it with the -b option.
