### ISSUE TITLE
Test CAT6 cable throughput/errors with Packetsender, how to...?

### ISSUE THREAD

**Issue by HubTode** [dannagle/PacketSender#135]
#### What OS?

- [ x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

I have a home with contractor-installed CAT6 that cannot be physically inspected and I suspect that one of the cables is damaged. It's barely hitting 30mbps and it's only about 50 feet, but it's in the wall and not accessible. It passes the basic continuity test. Looking for instruction to set up two Packetsender PCs with appropriate packet sending tests to verify the top speed and types of errors, so that I can seek a remedy. Also (and this is a long shot idea) would it be possible to sniff out a problem such as a kink using something like a Fluke toner?
Thanks in advance for help!

**Comment by dannagle** [comment]
Hello, 

Packet Sender is not a good tool to saturate a network. At best, it can send packets at around 10 Hz. Even damaged cables would yawn. Packet Sender is perfect for checking basic connectivity (which you've done). You've now exceed its use. 

Sorry I cannot help more.

**Comment by whitekn3** [comment]
This is an old thread, and it's been long enough since I used one so I don't remember details, but you can rent, or buy, a good quality cable tester that will let you measure the distance to a bad spot.  Usually accurate to a few feet.   Look for one with "Time Domain Reflectometer" (TDR).    Chance are the problem is not a "Kink" per se, but a stretched cable with an internal partial break.    The cable will pass a simple ohm meter test, past some traffic, but fail with real data at network speeds.

Obviously, a bad cable in a wall is still a problem. Even if you can pull in a new cable without tearing up the wall, you risk damaging the new cable by excessive tension.  But it would let you be able to demonstrate to a contractor:  "It is a cable problem and it's here..."
