### ISSUE TITLE
Enabling inbound port on Azure VM

### ISSUE THREAD

**Issue by oldbeeds** [dannagle/PacketSender#154]
Anyone experienced with configuring Azure VM to allow inbound TCP port for Packet Sender?

I have:
1) Enabled port in Network Security Group in Azure portal.
2) Enabled port in Windows Firewall on VM.
3) Installed and run Packet Sender on VM.

If I send a packet using PS on a remote computer it does not get received in PM on the VM.

I have done the same steps on a AWS VM which was successful.

Any ideas?

Thanks.

**Comment by dannagle** [comment]
I've not used Azure VMs. On my own personal VMs, I have seen problems if network access to the VM is set to "NAT" instead of "bridged" networking. That seems an unlikely configuration for a VM out in the cloud, but perhaps it is happening. Maybe a proxy is in the middle. 

This is a shot in the dark: I've seen the general bind "0.0.0.0" not work as expected if there are multiple network cards present. The master branch of Packet Sender supports IP-specific binding that might help. I have not released installers yet (will soon), but I could piece together a quick one-off for you.

**Comment by oldbeeds** [comment]
Thanks so much for the help and advice Dan. I just figured it out actually. There was a different listening service running on the Azure box which prevented my PS app from intercepting packets on that port. Packet Sender rules by the way!
Pete

**Comment by dannagle** [comment]
Awesome. Glad you got it working. Closing this ticket.
