### ISSUE TITLE
Timing issue with Wndows version?

### ISSUE THREAD

**Issue by kslbeso** [dannagle/PacketSender#16]
I am running the Aug 22 PacketSenderPortable version on a PC running Win XP.
I have a client where the socket connection to PacketSender was established by first sending an UDP message from PacketSender on an agreed upon port.
This client then sends UDP packages every 200 ms back to PacketSender.
Over time, PacketSender will bundle the display of these packages together, so that more and more packages seem to come at the same time.
I had to double-check that with WireShark, which then made it obvious that the packages actually are sent out every 200 ms, but that PacketSender will have increasing problems with showing these.
I don't know if this is a problem related to the PC I am running it on, but I was thinking since WireShark is able to capture the packages in time, why shouldn't PacketSender be able to do the same thing?
I can supply you with corresponding captures if you require.

Best regards,
Bertil Soderberg, Vasteras, Sweden

**Comment by kslbeso** [comment]
I just checked how PacketSender will be able to uphold a cyclical resend of UDP telegrams when at the same time receiving these 200 ms packages. With WireShark it could then be seen that the cyclicity of the sending goes down in relation to the problem of the bundling of the display of incoming packages.

If this is out of scope of your intention with PacketSender, you can freely just close this issue.
/Regards

**Comment by dannagle** [comment]
A couple versions back I updated Packet Sender to add a bit of intelligence to the packet capture mechanism for TCP. If two packets come in close to the same time from the same source, it would combine the the data and show it as 1 packet.

This would be the preferred behavior for a TCP stream because you'd want to see all the data together. It doesn't work so well for UDP. The code for the packet capture of TCP and UDP is routed through the same logic. 

I'll leave this issue open so I know to fix it on the UDP side.

**Comment by kslbeso** [comment]
In the same context I tried also to send UDP packets with a specified cyclicity (0.3 s) at the same time as the bundling of the received packets were made. It showed that the cyclicity of the sending was influenced by this also. With time it could take many seconds before the next outgoing UDP packet was sent (checked via WireShark). 
Maybe it's the same issue or it's just Windows having problem with these kinds of cycle times.
Just to let you know.
