### ISSUE TITLE
website doesn't mention Android version

### ISSUE THREAD

**Issue by jidanni** [dannagle/PacketSender#25]
https://packetsender.com/ juat says Linux, Windows, etc.

**Comment by jidanni** [comment]
Found app on f-droid. Please add to Play store.

**Comment by dannagle** [comment]
Android (and iOS) are mentioned in the documentation section. The source code for each is available here:
* https://github.com/dannagle/PacketSender-Android
* https://github.com/dannagle/PacketSender-iOS

The mobile versions have been abandoned because there are only 24 hours in the day. I don't make any money off this project. If a benevolent benefactor drops by, I may pick it up mobile support again.

**Comment by jidanni** [comment]
OK but maybe https://f-droid.org/wiki/page/com.packetsender.android etc.
there should warn that it has been abandoned.

Also so should
https://play.google.com/store/apps/details?id=com.grayson.packetsender
but oops I guess that isn't yours.

I see
https://en.wikipedia.org/wiki/Packet_Sender#Platforms
notes the abandoning of mobile versions, but maybe
https://packetsender.com/ should change

Download
Versions for Windows, Mac, and Linux can be found here.

to

Download
Versions for Windows, Mac, and Linux can be found here.
Android and IOS versions are no longer maintained, but source...

as lots of people will still wonder and search for them, thus needing
clarification right there under "Download".
