### ISSUE TITLE
[IDEA] Add date/time formatting customization in macros

### ISSUE THREAD

**Issue by Wheelztracker** [dannagle/PacketSender#308]
In macros Date and time formats are fixed. If it is customizable means it will be useful for most if the projects. For example i need my current date in the following format ddmmyyyy without any - or / in it. Like i need time as hhmmss without any : or-. Please consider this.

**Comment by Wheelztracker** [comment]
When this can be enhanced ? Any timeline ?

**Comment by dannagle** [comment]
When a feature does not have a sponsor, the timeline is "when there is spare time". It is hard to estimate because a sponsored feature will always jump ahead of it. Without a sponsor, this feature might get added in 8 months. With a sponsor, it can be added to the next release that is scheduled in 2 months. Early access copies can also be made available immediately after the feature is added if desired to have it even quicker. 

This feature is simple. It could be sponsored for $100 (paid using the PayPal donate link or through GitHub sponsors).

**Comment by Wheelztracker** [comment]
> When a feature does not have a sponsor, the timeline is "when there is spare time". It is hard to estimate because a sponsored feature will always jump ahead of it. Without a sponsor, this feature might get added in 8 months. With a sponsor, it can be added to the next release that is scheduled in 2 months. Early access copies can also be made available immediately after the feature is added if desired to have it even quicker.
> 
> This feature is simple. It could be sponsored for $100 (paid using the PayPal donate link or through GitHub sponsors).

I'm ready to sponsor this amount. i have few simple questions. 
Shall i pay $50 advance and $50 after completion ? 
Can you provide this feature only to us? 
Also i need the timeline that how long it could take once after making the payment? 
I'll explain the features which i need. 
Current Date in the format of ddmmyyyy and for time i need GMT time hhmmss. should not use any Punctuations like ( : , - / ) in between the date and time format.

**Comment by dannagle** [comment]
Email me at hello@packetsender.com if you have specific needs.

**Comment by dannagle** [comment]
This will be in the next release.  Go to Settings->Smart Responses to customize.
