### ISSUE TITLE
Request: Option to disable the fixed size for the ASCII row.

### ISSUE THREAD

**Issue by TronicLabs** [dannagle/PacketSender#95]
https://github.com/dannagle/PacketSender/blob/development/src/mainwindow.cpp#L1478-L1480

Can we have an option to set the desidered fixed size or set it as auto-size like the HEX row?

**Comment by Galileo53** [comment]
I don't know if this is the same issue, but I will add this here as a comment:
Can you please DO NOT re-size the columns in the log window on each event.
The response I am looking for is received in ascii, but it has a relatively long header so the data of interest is always hidden behind the HEX column. Manually resizing the ASCII column works, but at the next event the columns are reset and data is hidden again.
It is also not possible to remove the HEX column completely, or exchange HEX and ASCII so that ASCII can have the rest of the line...

**Comment by dannagle** [comment]
Fixed in development branch.
